[build]
command = "npm run build"
publish = "dist"
base = "."

[build.environment]
NODE_VERSION = "18"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/uploads/*"
to = "https://travel-guide-server-production-ea9a.up.railway.app/uploads/:splat"
status = 200
